name: Scheduled Backup
on:
  schedule:
    - cron: "0 5 * * *"

jobs:
  create_backup:
    runs-on: ubuntu-latest
    services:
      hub:
        image: selenium/standalone-chrome
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
        ports:
          - 4444:4444

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          pip install -r requirements.txt
      - name: Create Backup
        env:
          GPORTAL_EMAIL: ${{ tomaszstrnad@seznam.cz }}
          GPORTAL_PASSWORD: ${{ LachtaN123 }}
          GPORTAL_BACKUP_URL: ${{ https://www.g-portal.com/eur/server/minecraft/4152289/system/backup }}
        run: |
          python app.py
